-- Intentionally left as a no-op.
--
-- The previous draft broadened Content Studio and Storage write/delete access
-- to every authenticated account. Keep the existing company-user policies
-- instead; administrator access should be granted explicitly, not globally.
